spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  properties.hibernate.format_sql: true
  show-sql: true

spring.datasource:
  hikari.maximum-pool-size: 4
  url: ${DB_URL}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  driver-class-name: org.postgresql.Driver

jwt:
  secret-key: ${JWT_KEY}
  # 30 days
  token.expired-time-ms: ${JWT_EXPIRED_TIME_MS}

spring.redis.url: ${REDIS_URL}

spring:
  kafka:
      consumer:
        properties.spring.json.trusted.packages: "*"
        bootstrap-servers: ${KAFKA_HOST}
        group-id: alarm
        auto-offset-reset: latest
        key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      listener:
        ack-mode: MANUAL
      producer:
        bootstrap-servers: ${KAFKA_HOST}
        key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      topic:
        alarm: alarm
